
import __ASTRO_IMAGE_IMPORT_0 from "../../assets/blog/angular-cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftop-10-reasons-to-upgrade-your-angular-application.md";
import __ASTRO_IMAGE_IMPORT_1 from "../../assets/blog/ionic.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fimprove-your-ionic-app-performance.md";
import __ASTRO_IMAGE_IMPORT_2 from "../../assets/blog/jumpy-theme-banner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjumpy-theme-customizer.md";
import __ASTRO_IMAGE_IMPORT_3 from "../../assets/blog/leetcode-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2-leetcode-kids-with-the-greates-number-of-candies-solution.md";
import __ASTRO_IMAGE_IMPORT_4 from "../../assets/blog/phaser-camera-cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fphaser-character-movement-camera.md";
import __ASTRO_IMAGE_IMPORT_5 from "../../assets/blog/phaser-what-cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fphaser-why-what-how.md";
import __ASTRO_IMAGE_IMPORT_6 from "../../assets/blog/svgpatternsbanner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsvg-patterns.md";
import __ASTRO_IMAGE_IMPORT_7 from "../../assets/blog/webpack.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flazy-loading-modules-with-webpack.md";
import __ASTRO_IMAGE_IMPORT_8 from "../../assets/projects/alertbeatbanner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Falertbeat.md";
import __ASTRO_IMAGE_IMPORT_9 from "../../assets/projects/jumpythemeproject.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fjumpy-theme-customizer.md";
import __ASTRO_IMAGE_IMPORT_10 from "../../assets/projects/mccandles.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fmc-candles.md";
export default new Map([["../../assets/blog/angular-cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftop-10-reasons-to-upgrade-your-angular-application.md", __ASTRO_IMAGE_IMPORT_0], ["../../assets/blog/ionic.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fimprove-your-ionic-app-performance.md", __ASTRO_IMAGE_IMPORT_1], ["../../assets/blog/jumpy-theme-banner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjumpy-theme-customizer.md", __ASTRO_IMAGE_IMPORT_2], ["../../assets/blog/leetcode-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2-leetcode-kids-with-the-greates-number-of-candies-solution.md", __ASTRO_IMAGE_IMPORT_3], ["../../assets/blog/phaser-camera-cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fphaser-character-movement-camera.md", __ASTRO_IMAGE_IMPORT_4], ["../../assets/blog/phaser-what-cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fphaser-why-what-how.md", __ASTRO_IMAGE_IMPORT_5], ["../../assets/blog/svgpatternsbanner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsvg-patterns.md", __ASTRO_IMAGE_IMPORT_6], ["../../assets/blog/webpack.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flazy-loading-modules-with-webpack.md", __ASTRO_IMAGE_IMPORT_7], ["../../assets/projects/alertbeatbanner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Falertbeat.md", __ASTRO_IMAGE_IMPORT_8], ["../../assets/projects/jumpythemeproject.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fjumpy-theme-customizer.md", __ASTRO_IMAGE_IMPORT_9], ["../../assets/projects/mccandles.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fmc-candles.md", __ASTRO_IMAGE_IMPORT_10]]);
		